version: '3.6'
secrets:
  postgres-pass:
    file: .local/postgres_pass
  postgres-user:
    file: .local/postgres_user
services:
  postgres:
    image: arribada/smart-connect-postgis:v0.0.1
    secrets:
      - postgres-user
      - postgres-pass
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user # The username is also used for the db name.
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-pass
    volumes:
    - postgres:/var/lib/postgresql/data
    - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  tomcat:
    image: arribada/smart-connect:v0.0.1
    ports:
    - "8443:8443"
    volumes:
    - tomcat:/home/SMARTconnect/filestore/
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
    secrets:
      - postgres-user
      - postgres-pass
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-pass
volumes:
  tomcat:
  postgres:
