version: 2.1

orbs:
  docker: arribada/docker@0.0.15
workflows:
  publish:
    jobs:
      - docker/publish:
          containerName: smart-connect
          buildContext: tomcat
          afterCheckout:
            - run: cd tomcat && wget https://github.com/arribada/SMARTConnect/releases/download/tomcat-app-v0.0.1/server.war
          context: org-context
          filters:
            # branches:
            #     only:
            #       - master
            #   ignore: /.*/
            tags:
              only: /v\d+\.\d+\.\d+$/
      - docker/publish:
          containerName: smart-connect-postgis
          buildContext: postgres
          context: org-context
          filters:
            # branches:
            #     only: 
            #       - master
            # #   ignore: /.*/
            tags:
              only: /v\d+\.\d+\.\d+$/
