version: 2.1

orbs:
  docker: arribada/docker@0.0.12
workflows:
  publish:
    jobs:
      - docker/publish:
          containerName: smart-connect
          buildContext: ./tomcat
          context: org-context
          filters:
            branches:
                only:
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/
      - docker/publish:
          containerName: smart-connect-postgis
          buildContext: ./postgres
          context: org-context
          filters:
            branches:
                only: 
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/
